<a href="https://colab.research.google.com/github/PalakAggarwal13/PyTorch-DeepLearning/blob/main/PyTorch_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
print(torch.__version__)

2.6.0+cu124


In [8]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [9]:
t1.dtype

torch.float32

In [10]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [12]:
t2.dtype

torch.float32

In [13]:
t3 = torch.tensor([[1.,2,3],[4,5,6],[7,8,9]])
t3

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [14]:
t3.dtype

torch.float32

In [15]:
t4 = torch.tensor([
    [[11.,12,13],
     [14,15,16]],
    [[17,18,19],
     [20,21,22]]
])
t4

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[17., 18., 19.],
         [20., 21., 22.]]])

In [16]:
t4.dtype

torch.float32

In [17]:
t1.shape

torch.Size([])

In [18]:
t2.shape

torch.Size([4])

In [19]:
t3.shape

torch.Size([3, 3])

In [20]:
t4.shape

torch.Size([2, 2, 3])

In [5]:
x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad = True)
b = torch.tensor(5. , requires_grad = True)

In [6]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [7]:
y.backward()

In [8]:
print("dy/dx:" , x.grad)
print("dy/dw:" , w.grad)
print("dy/db:" , b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [9]:
import numpy as np

x = np.array([[1.,2,3],[4,5,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
y = torch.from_numpy(x)            #or you can do torch.tensor(x)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [11]:
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [12]:
z = y.numpy()
z

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [14]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [15]:
inputs = torch.tensor(inputs)
targets = torch.tensor(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [16]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.7362,  0.8083,  0.4137],
        [-0.1021, -1.4533,  1.6934]], requires_grad=True)
tensor([ 1.0912, -0.4246], requires_grad=True)


In [17]:
def model(x):
  return x @ w.t() + b

In [18]:
preds = model(inputs)
preds

tensor([[  19.2930,  -32.4330],
        [  31.7035,  -29.2283],
        [  69.3464, -105.8317],
        [ -23.9378,  -10.6764],
        [  56.8485,  -28.4470]], grad_fn=<AddBackward0>)

In [20]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [21]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff * diff) / diff.numel()

In [22]:
loss = mse(preds , targets)
print(loss)  # full tensor

tensor(11898.9473, grad_fn=<DivBackward0>)


In [23]:
loss.backward()

In [24]:
print("dl/dw : " , w.grad)
print("dl/db : " , b.grad)

dl/dw :  tensor([[ -3871.1133,  -3971.3828,  -2508.7183],
        [-11028.7168, -13306.3115,  -7735.3584]])
dl/db :  tensor([ -45.5493, -133.3233])


In [25]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# **GRADIENT DESCENT**

In [58]:
import torch

inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

lr = 1e-5

def mse(preds,targets):
  return torch.mean((preds-targets)**2)

for epoch in range(100):

  preds = inputs @ w.t() + b
  loss  = mse(preds,targets)

  loss.backward()

  with torch.no_grad():
    w -= lr * w.grad
    b -= lr * b.grad

    w.grad.zero_()
    b.grad.zero_()

  if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.4f} ,  w =\n{w} , b = {b}")

Epoch 0: Loss = 6584.4351 ,  w =
tensor([[ 1.2017, -0.9096,  0.3172],
        [ 0.2598,  0.3758, -0.4398]], requires_grad=True) , b = tensor([1.4545, 0.1966], requires_grad=True)
Epoch 10: Loss = 1949.7581 ,  w =
tensor([[ 1.2615, -0.6301,  0.4422],
        [ 0.4793,  0.6824, -0.2541]], requires_grad=True) , b = tensor([1.4557, 0.1994], requires_grad=True)
Epoch 20: Loss = 1649.3287 ,  w =
tensor([[ 1.1811, -0.5145,  0.4690],
        [ 0.4780,  0.7474, -0.2167]], requires_grad=True) , b = tensor([1.4552, 0.1997], requires_grad=True)
Epoch 30: Loss = 1457.6589 ,  w =
tensor([[ 1.0867, -0.4264,  0.4816],
        [ 0.4479,  0.7773, -0.2001]], requires_grad=True) , b = tensor([1.4546, 0.1995], requires_grad=True)
Epoch 40: Loss = 1290.1519 ,  w =
tensor([[ 0.9955, -0.3466,  0.4917],
        [ 0.4155,  0.8008, -0.1866]], requires_grad=True) , b = tensor([1.4539, 0.1994], requires_grad=True)
Epoch 50: Loss = 1142.5428 ,  w =
tensor([[ 0.9095, -0.2721,  0.5009],
        [ 0.3845,  0.8221, -0.